// <auto-generated />
using System;
using DevOps.Util.DotNet.Triage;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DevOps.Util.DotNet.Triage.Migrations
{
    [DbContext(typeof(TriageContext))]
    [Migration("20200423162629_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DevOps.Util.DotNet.Triage.ModelBuild", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("BuildNumber")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FinishTime")
                        .HasColumnType("smalldatetime");

                    b.Property<string>("GitHubOrganization")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GitHubRepository")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ModelBuildDefinitionId")
                        .HasColumnType("int");

                    b.Property<int?>("PullRequestNumber")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("smalldatetime");

                    b.HasKey("Id");

                    b.HasIndex("ModelBuildDefinitionId");

                    b.ToTable("ModelBuilds");
                });

            modelBuilder.Entity("DevOps.Util.DotNet.Triage.ModelBuildDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AzureOrganization")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AzureProject")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("DefinitionId")
                        .HasColumnType("int");

                    b.Property<string>("DefinitionName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AzureOrganization", "AzureProject", "DefinitionId")
                        .IsUnique()
                        .HasFilter("[AzureOrganization] IS NOT NULL AND [AzureProject] IS NOT NULL");

                    b.ToTable("ModelBuildDefinitions");
                });

            modelBuilder.Entity("DevOps.Util.DotNet.Triage.ModelTimelineItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BuildNumber")
                        .HasColumnType("int");

                    b.Property<string>("Line")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModelBuildId")
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ModelTimelineQueryId")
                        .HasColumnType("int");

                    b.Property<string>("TimelineRecordName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ModelBuildId");

                    b.HasIndex("ModelTimelineQueryId");

                    b.ToTable("ModelTimelineItems");
                });

            modelBuilder.Entity("DevOps.Util.DotNet.Triage.ModelTimelineQuery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GitHubOrganization")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GitHubRepository")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("IssueNumber")
                        .HasColumnType("int");

                    b.Property<string>("SearchText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GitHubOrganization", "GitHubRepository", "IssueNumber")
                        .IsUnique();

                    b.ToTable("ModelTimelineQueries");
                });

            modelBuilder.Entity("DevOps.Util.DotNet.Triage.ModelTimelineQueryComplete", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ModelBuildId")
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ModelTimelineQueryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ModelBuildId");

                    b.HasIndex("ModelTimelineQueryId", "ModelBuildId")
                        .IsUnique()
                        .HasFilter("[ModelBuildId] IS NOT NULL");

                    b.ToTable("ModelTimelineQueryCompletes");
                });

            modelBuilder.Entity("DevOps.Util.DotNet.Triage.ModelBuild", b =>
                {
                    b.HasOne("DevOps.Util.DotNet.Triage.ModelBuildDefinition", "ModelBuildDefinition")
                        .WithMany()
                        .HasForeignKey("ModelBuildDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DevOps.Util.DotNet.Triage.ModelTimelineItem", b =>
                {
                    b.HasOne("DevOps.Util.DotNet.Triage.ModelBuild", "ModelBuild")
                        .WithMany()
                        .HasForeignKey("ModelBuildId");

                    b.HasOne("DevOps.Util.DotNet.Triage.ModelTimelineQuery", "ModelTimelineQuery")
                        .WithMany("ModelTimelineItems")
                        .HasForeignKey("ModelTimelineQueryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DevOps.Util.DotNet.Triage.ModelTimelineQueryComplete", b =>
                {
                    b.HasOne("DevOps.Util.DotNet.Triage.ModelBuild", "ModelBuild")
                        .WithMany()
                        .HasForeignKey("ModelBuildId");

                    b.HasOne("DevOps.Util.DotNet.Triage.ModelTimelineQuery", "ModelTimelineQuery")
                        .WithMany("ModelTimelineQueryCompletes")
                        .HasForeignKey("ModelTimelineQueryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
